### ISSUE TITLE
Error deploy-jetton  failed: upload image: [object Object]

### ISSUE THREAD

**Issue by gnomski** [ton-community/assets-sdk#16]
I have an error when I run `assets-cli deploy-jetton` 
Attempt 1 failed: upload image: [object Object]
Attempt 2 failed: upload image: [object Object]
Attempt 3 failed: upload image: [object Object]
Error: Exceeded number of retries
    at retry (C:\..\npm\node_modules\@ton-community\assets-sdk\dist\cli\common.js:176:11)
    at async Object.main (C:\..\npm\node_modules\@ton-community\assets-sdk\dist\cli\deploy-jetton.js:79:23)
I use pinata storage and IPFS gateway

**Comment by omanhom** [comment]
I has the same error，how IPFS_GATEWAY and IPFS_GATEWAY_API_KEY Where to obtain?
